window.infoBubblesDatas = [
  // HTML
  "VERVRVER ZFFZER Z ZF FVFRVRZ",
  // CSS
  "VERVRVER ZFFZER Z ZF FVFRVRZ",
  // SASS
  "VERVRVER ZFFZER Z ZF FVFRVRZ",
  // JavaScript
  "VERVRVER ZFFZER Z ZF FVFRVRZ",
  // React
  "VERVRVER ZFFZER Z ZF FVFRVRZ",
  // Node.JS
  "cebcjkbec zkecbzkejcb",
  // Express.JS
  "VERVRVER ZFFZER Z ZF FVFRVRZ",
  // MongoDB
  "VERVRVER ZFFZER Z ZF FVFRVRZ",
  // PHP
  "VERVRVER ZFFZER Z ZF FVFRVRZ",
  // Git
  "VERVRVER ZFFZER Z ZF FVFRVRZ",
  // GitHub
  "VERVRVER ZFFZER Z ZF FVFRVRZ",
  // Figma
  "VERVRVER ZFFZER Z ZF FVFRVRZ",
  // Notion
  "VERVRVER ZFFZER Z ZF FVFRVRZ",
  // Postman
  "VERVRVER ZFFZER Z ZF FVFRVRZ",
];
